### ISSUE TITLE
Formatting of Expected Results on SOW-89

### ISSUE THREAD

**Issue by ahewitt-glasswall** [filetrust/gw-sow-presentation#24]

**Comment by lukeR4** [comment]
![2020-02-26_11h27_54](https://user-images.githubusercontent.com/44669617/75340796-10932a80-588b-11ea-9008-1ee675e0fd57.png)

**Comment by ahewitt-glasswall** [comment]
Fixed this by wrapping the unformatted code with a <pre></pre> tag in JIRA.

![image](https://user-images.githubusercontent.com/59472395/75348809-653ea180-589b-11ea-8e83-95a63ad91855.png)

**Comment by lukeR4** [comment]
Looks good. Closing
