### ISSUE TITLE
The HTML OL element is not rendered in Interactive Scheme of Work

### ISSUE THREAD

**Issue by mobrien-gw** [filetrust/gw-sow-presentation#45]
The following HTML should list each file name pre-pended with a bullet point:

```
<ul>
<li>TestFile_1_corrupted_jpeg_with_png_magic_number</li>
<li>TestFile_2_doc_file_with_no_extension</li>
</ul>
```

Paste it into [Real-Time HTML Editor](https://htmledit.squarefree.com/) > to verify.

When rendered in [Interactive Scheme of Work](https://filetrust.github.io/gw-sow-presentation/) no bullet points are present.

**Comment by tpilvelis-gw** [comment]
could you point me to which SOW item that contains this @mobrien-gw

**Comment by mikebenton-gw** [comment]
This is css - leave with me

**Comment by mikebenton-gw** [comment]
OLs appear to render fine it's the ULs that had hidden list item styles due to the menu requiring them hidden.
