### ISSUE TITLE
Jamie Pool Has Content to add in th Setup

### ISSUE THREAD

**Issue by tpilvelis-gw** [filetrust/gw-sow-presentation#71]
![image](https://user-images.githubusercontent.com/59439145/75664945-3d6c8680-5c6b-11ea-93ed-1a2892aea3f9.png)

**Comment by jpoolGW** [comment]
![image](https://user-images.githubusercontent.com/60877176/75690471-cf3fb800-5c9a-11ea-834c-39b0add0980c.png)
Has been added to Enhancement 1 set up. Closing issue
